spring.application.name=demo
###To enable h2 database
spring.h2.console.enabled=true

###To set jdbc
spring.datasource.url=jdbc:h2:mem:suvam

###To see sql commands and queries
spring.jpa.show-sql=true

###To prevent duplicate keys on every restart
spring.jpa.defer-datasource-initialization=true